config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  resources :users
  get '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
  belongs_to :user
end

app/models/liquor.rb
class Liquor < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
     attr_accessor :remember_token
     validates :name,  presence: true, length: { maximum: 50 }
     validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
     has_secure_password
     
     class << self
          # 渡された文字列のハッシュ値を返す
          def digest(string)
               cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                            BCrypt::Engine.cost
               BCrypt::Password.create(string, cost: cost)
          end

          # ランダムなトークンを返す
          def new_token
               SecureRandom.urlsafe_base64
          end
     end

     # 永続セッションのためにユーザーをデータベースに記憶する
     def remember
          self.remember_token = User.new_token
          update_attribute(:remember_digest, User.digest(remember_token))
     end

     # ユーザーのログイン情報を破棄する
     def forget
          update_attribute(:remember_digest, nil)
     end

     # トークンがダイジェストと一致したらtrueを返す
     def authenticated?(attribute, token)
          digest = send("#{attribute}_digest")
          return false if digest.nil?
          BCrypt::Password.new(digest).is_password?(token)
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    private
  
    # ログイン済みユーザーかどうか確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]

  # GET /diaries
  def index
    @diaries = Diary.all
  end

  # GET /diaries/1
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  def create
    @diary = Diary.new(diary_params)

    if @diary.save
      redirect_to @diary, notice: 'Diary was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /diaries/1
  def update
    if @diary.update(diary_params)
      redirect_to @diary, notice: 'Diary was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /diaries/1
  def destroy
    @diary.destroy
    redirect_to diaries_url, notice: 'Diary was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def diary_params
      params.require(:diary).permit(:week, :date, :bedtime, :wakeuptime, :time_beforesleep, :awaken_times, :liquor_type, :liquor_num, :feeling, :sleep_quality, :naptime, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
      if user && user.authenticate(params[:session][:password])
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        flash.now[:danger] = 'Invalid username/password combination' 
        render 'new'
      end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  
  # GET /users
  def index
    if @user.admin
      @users = User.all
    elsif 
      @users = Users.where(id: @user.id)
    end
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t('flash.user_create_success')
      redirect_to @user
    else
      render :new 
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.' 
    else
      render :edit 
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "SleepDiary"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
    # 渡されたユーザーでログインする
    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
      end

    # 現在ログイン中のユーザーを返す、もしくはクッキーに永続化されたユーザーを返す
    def current_user
        if (user_id = session[:user_id])
        @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
        user = User.find_by(id: user_id)
        if user && user.authenticated?(:remember, cookies[:remember_token])
            log_in user
            @current_user = user
        end
        end
    end
    
    # ユーザーのセッションを永続的にする
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
    
    # ユーザーがログインしていればtrue、その他ならfalseを返す
    def logged_in?
        !current_user.nil?
    end
    
    # 永続的セッションを破棄する
    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

      # 記憶したURL (もしくはデフォルト値) にリダイレクト
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

    # アクセスしようとしたURLを覚えておく
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diaries/_form.html.erb
<%= form_with(model: diary, local: true) do |form| %>
  <% if diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
        <% diary.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :week %>
    <%= form.number_field :week %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :bedtime %>
    <%= form.time_select :bedtime %>
  </div>

  <div class="field">
    <%= form.label :wakeuptime %>
    <%= form.time_select :wakeuptime %>
  </div>

  <div class="field">
    <%= form.label :time_beforesleep %>
    <%= form.time_select :time_beforesleep %>
  </div>

  <div class="field">
    <%= form.label :awaken_times %>
    <%= form.number_field :awaken_times %>
  </div>

  <div class="field">
    <%= form.label :liquor_type %>
    <%= form.number_field :liquor_type %>
  </div>

  <div class="field">
    <%= form.label :liquor_num %>
    <%= form.number_field :liquor_num %>
  </div>

  <div class="field">
    <%= form.label :feeling %>
    <%= form.number_field :feeling %>
  </div>

  <div class="field">
    <%= form.label :sleep_quality %>
    <%= form.number_field :sleep_quality %>
  </div>

  <div class="field">
    <%= form.label :naptime %>
    <%= form.time_select :naptime %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/edit.html.erb
<h1>Editing Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diaries</h1>

<table>
  <thead>
    <tr>
      <th>Week</th>
      <th>Date</th>
      <th>Bedtime</th>
      <th>Wakeuptime</th>
      <th>Time beforesleep</th>
      <th>Awaken times</th>
      <th>Liquor type</th>
      <th>Liquor num</th>
      <th>Feeling</th>
      <th>Sleep quality</th>
      <th>Naptime</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %>
      <tr>
        <td><%= diary.week %></td>
        <td><%= diary.date %></td>
        <td><%= diary.bedtime %></td>
        <td><%= diary.wakeuptime %></td>
        <td><%= diary.time_beforesleep %></td>
        <td><%= diary.awaken_times %></td>
        <td><%= diary.liquor_type %></td>
        <td><%= diary.liquor_num %></td>
        <td><%= diary.feeling %></td>
        <td><%= diary.sleep_quality %></td>
        <td><%= diary.naptime %></td>
        <td><%= diary.user_id %></td>
        <td><%= link_to 'Show', diary %></td>
        <td><%= link_to 'Edit', edit_diary_path(diary) %></td>
        <td><%= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diary', new_diary_path %>

app/views/diaries/new.html.erb
<link rel="stylesheet" href="https://cdn.rawgit.com/jonthornton/jquery-timepicker/3e0b283a/jquery.timepicker.min.css">
<script src="https://cdn.rawgit.com/jonthornton/jquery-timepicker/3e0b283a/jquery.timepicker.min.js"></script>

<h1>New Diary</h1>

<%= render 'form', diary: @diary %>

<%= link_to 'Back', diaries_path %>

app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Week:</strong>
  <%= @diary.week %>
</p>

<p>
  <strong>Date:</strong>
  <%= @diary.date %>
</p>

<p>
  <strong>Bedtime:</strong>
  <%= @diary.bedtime %>
</p>

<p>
  <strong>Wakeuptime:</strong>
  <%= @diary.wakeuptime %>
</p>

<p>
  <strong>Time beforesleep:</strong>
  <%= @diary.time_beforesleep %>
</p>

<p>
  <strong>Awaken times:</strong>
  <%= @diary.awaken_times %>
</p>

<p>
  <strong>Liquor type:</strong>
  <%= @diary.liquor_type %>
</p>

<p>
  <strong>Liquor num:</strong>
  <%= @diary.liquor_num %>
</p>

<p>
  <strong>Feeling:</strong>
  <%= @diary.feeling %>
</p>

<p>
  <strong>Sleep quality:</strong>
  <%= @diary.sleep_quality %>
</p>

<p>
  <strong>Naptime:</strong>
  <%= @diary.naptime %>
</p>

<p>
  <strong>User:</strong>
  <%= @diary.user_id %>
</p>

<%= link_to 'Edit', edit_diary_path(@diary) %> |
<%= link_to 'Back', diaries_path %>

app/views/layouts/_default.html.erb
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 

app/views/layouts/_header.html.erb
<header class="navbar fixed-top navbar-dark bg-dark">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark container">
    <%= link_to t('util.application_name'), root_path, id: "logo" , class:'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to t('util.home'), root_path, class: "nav-link"  %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
        <% if logged_in? %>
          <%= link_to t('util.logout'), logout_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to t('util.login'), login_path, class: "nav-link" %>
        <% end %> 
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/default' %> 
  </head>
  <body>
     <%= render 'layouts/header' %>
     <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, t('.title')) %>
<div class="center">
    <div class="main-contents">
        <p>日々の睡眠を日記化して、改善を図る手助けのサイトです。</p>
        <p>https://www.sogensha.co.jp/productlist/detail?id=3525 の睡眠日記部分をweb化する試みです。</p>
      　<%= link_to t('.signup'), signup_path , class: "btn btn-lg btn-primary" %>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name ,class: 'form-control' %>

  <%= form.label :password %>
  <%= form.password_field :password , class: 'form-control' %>

  <%= form.label :password_confirmation, "Confirmation" %>
  <%= form.password_field :password_confirmation , class: 'form-control' %>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>